<program>
    <?php 
    $title = $program->getTitle();
    $this->headTitle($title);
    ?>
    <h2><?php echo $this->escapeHtml($title); ?></h2>
	
        <?php
        
	//$getCount = $program->getViewCount(); echo $getCount . ' ' . $this->translate('views');
	echo $program->getFullText();?>
</program>
    <?php if($program->getAllowProducts()){ ?>
        <hr>
        <h3><?php echo $this->translate('Products'); ?></h3>
        <?php if($user = $this->identity()) :?>
            <p><a href="<?php echo $this->url('bkd-rwd/default',
                            array('controller' => 'product', 'action'=>'add', 'id' => $program->getId()), true);?>">
                    <?php echo $this->translate('Add new product.'); ?>
                </a>
            </p>
        <?php endif; ?>
        <table class="table">
        <?php
        echo '<tr>';
        echo '<th>Title</th>';
        echo '    <th>Amount</th>';
        echo '    <th>Date</th>';
        echo '  <th>Action</th>';
        echo '    <th>&nbsp;</th>';
        echo '</tr>';
            ?>
            <?php foreach ($products as $product) : ?>
                <tr>

                <td><h4><?php echo $this->escapeHtml($product->getTitle());?></h4></td>
                 <td><?php echo $this->escapeHtml($product->getText());?></td>
                 <td><input type="text" id="date<?php echo $product->getId()?>" class="datepick"></td>
                  <td>
                      
                    <?php
                    //--- Check if Author or Admin and let them edit/delete program.
                    if($user && is_object($program->getAuthor()) && is_object($product->getAuthor())) :
                        if ($user->getId()==$program->getAuthor()->getId() || $user->getId()==$product->getAuthor()->getId()) : ?>
                            <p>
                                <a href="<?php echo $this->url('bkd-rwd/default',
                                    array('controller' => 'product', 'action'=>'edit', 'id2' => $product->getId()), true);?>"> Edit | </a>
                                <a href="<?php echo $this->url('bkd-rwd/default',
                                    array('controller' => 'product', 'action'=>'delete', 'id2' => $product->getId()), true);?>" onclick="return confirm('Do you really want to delete the record?')">Delete</a>
                            </p>
                    <?php endif;
                    endif; ?>


                  </td>


            <td>

            <?php
        
        echo $this->reward(
                $product->getReward(),
                $this->url('bkd-rwd/default', array('controller' => 'product', 'action'=>'reward', 'id' => $product->getId(), 'id2' => 1)),
                $this->url('bkd-rwd/default', array('controller' => 'product', 'action'=>'reward', 'id' => $product->getId(), 'id2' => 0))
        );
        
   // $getCount = $program->getViewCount(); echo $getCount . ' ' . $this->translate('views');
   // echo $program->getFullText();
        ?>
               </td>
                </tr>
            <?php endforeach; ?>
                
        </table>
            
    <?php }else{ ?>
        <hr>
        <p><?php echo $this->translate('Products are disabled for this program'); ?></p>
    <?php }  ?>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <script>
 $('.datepick').each(function(){
    $(this).datepicker();
 });

$('a').click(function (event){ 
     event.preventDefault(); 
     var url_parts = $(this).attr('href').replace(/\/\s*$/,'').split('/');
     var date_id =  "date"+url_parts[4];
     var date_value = $('#'+date_id).val();
     console.log(date_value);
     //console.log(url_parts[4]);
     $.ajax({
        url: $(this).attr('href'),
        type: "POST",
        data: { 'date': date_value},
        success: function(response) {
            console.log(response)
        }
     })
     return false; //for good measure
});


</script>