<?php
$title = 'My translations';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
<!-- <a href="<?php echo $this->url('bkd-rwd/default', array('controller' => 'translation', 'action'=>'add')); /*NOtice without true no param is send*/?>">Add new translation</a> -->
    <a href="<?php echo $this->url('bkd-rwd/default', array('controller' => 'program', 'action'=>'index'), false);?>">&lt; Back to the programs | </a>
    <a href="<?php echo $this->url('bkd-rwd/default', array('controller' => 'translation', 'action'=>'add'), true);?>">Add new translation</a>
</p>

<table class="table">
<tr>
<th>Title</th>
    <th>Intro Text</th>
    <th>Author</th>
    <th>Language</th>
	<th>Created</th>
    <th>&nbsp;</th>
</tr>'

<?php $program = $programs[0];?>
<?php $translations = $program->getChildren();?>

<?php foreach ($translations as $program) : ?>
<tr>
    <td><?php echo $this->escapeHtml($program->getTitle());?></td>
    <td><?php echo $this->escapeHtml($program->getIntrotext());?></td>
    <td><?php if (is_object($program->getAuthor())) echo $this->escapeHtml($program->getAuthor()->getUsername());?></td>
    <td><?php if (is_object($program->getLanguage())) echo $this->escapeHtml($program->getLanguage()->getName());?></td>
    <td><?php echo $this->escapeHtml($program->getCreated()->format('Y-m-d H:i:s'));?></td><!-- Notice: getCreated() returns an object convert to string -->
    <td>
        <a href="<?php echo $this->url('bkd-rwd/default', // SUPER IMPORTANT use bkd-rwd/<segment> NOT ONLY bkd-rwd
            array('controller' => 'product', 'action'=>'index', 'id' => $program->getId()));?>">Products</a>
        <a href="<?php echo $this->url('bkd-rwd/default', // SUPER IMPORTANT use bkd-rwd/<segment> NOT ONLY bkd-rwd
            array('controller' => 'translation', 'action'=>'view', 'id2' => $program->getId()), true);?>">View</a>
		<a href="<?php echo $this->url('bkd-rwd/default', // SUPER IMPORTANT use bkd-rwd/<segment> NOT ONLY bkd-rwd
            array('controller' => 'translation', 'action'=>'edit', 'id2' => $program->getId()), true);?>">Edit</a>
        <a href="<?php echo $this->url('bkd-rwd/default', // SUPER IMPORTANT use bkd-rwd/<segment>
            array('controller' => 'translation', 'action'=>'delete', 'id2' => $program->getId()), true);?>" onclick="return confirm('Do you really want to delete this translation?')">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>