<program>
    <?php 
    $title = $program->getTitle();
    $this->headTitle($title);
    ?>
    <h2><?php echo $this->escapeHtml($title); ?></h2>
	<p><?php
		if(!$hasUserVoted)
		{
			 ?></p>
	
	<a href="<?php echo $this->url('bkd-rwd/default',
                            array('controller' => 'program', 'action'=>'vote', 'id' => $program->getId(), 'id2' => 1), true);?>">
                    <?php echo $this->translate('Like');  ?>
                </a>
	<a href="<?php echo $this->url('bkd-rwd/default',
                            array('controller' => 'program', 'action'=>'vote', 'id' => $program->getId(), 'id2' => 0), true);?>">
                    <?php echo $this->translate('Dislike');  ?>
                </a>
    <p><?php } 
	else if($hasUserVoted == 'no')
	{
		echo $this->translate('You have no permission for voting!');
	}
	else
	{
		echo $this->translate('You have already voted!');
	}
	?>
	<p>
	<?php $getLikeVotes = $program->getVote()->getLikesCount(); echo 'Likes: '. $getLikeVotes ;
	 $getDislikeVotes = $program->getVote()->getDislikesCount(); echo 'Dislikes: '. $getDislikeVotes;
	?>
	</p>
	<?php
	$getCount = $program->getViewCount(); echo $getCount.' times previewed this Program.';
	echo '</p><p>';
	echo $program->getFullText();
	echo '</p>';?>
</program>
    <?php if($program->getAllowProducts()){ ?>
        <hr>
        <h3><?php echo $this->translate('Products'); ?></h3>
        <?php if($user = $this->identity()) :?>
            <p><a href="<?php echo $this->url('bkd-rwd/default',
                            array('controller' => 'product', 'action'=>'add', 'id' => $program->getId()), true);?>">
                    <?php echo $this->translate('Add new product.'); ?>
                </a>
            </p>
        <?php endif; ?>
        <ul>
            
            <?php foreach ($products as $product) : ?>
                <li>
                    <h4><?php echo $this->escapeHtml($product->getTitle());?></h4>
                    <span>
                        <?php
                            echo $product->getCreated()->format('F j, Y H:i'); 
                            if (is_object($product->getAuthor())) echo ' by ' . $this->escapeHtml($product->getAuthor()->getUsername());
                        ?>
                    </span>
                    <p><?php echo $this->escapeHtml($product->getText());?></p>
                    <?php
                    //--- Check if Author or Admin and let them edit/delete program.
                    if($user && is_object($program->getAuthor()) && is_object($product->getAuthor())) :
                        if ($user->getId()==$program->getAuthor()->getId() || $user->getId()==$product->getAuthor()->getId()) : ?>
                            <p>
                                <a href="<?php echo $this->url('bkd-rwd/default',
                                    array('controller' => 'product', 'action'=>'edit', 'id2' => $product->getId()), true);?>"> Edit | </a>
                                <a href="<?php echo $this->url('bkd-rwd/default',
                                    array('controller' => 'product', 'action'=>'delete', 'id2' => $product->getId()), true);?>" onclick="return confirm('Do you really want to delete the record?')">Delete</a>
                            </p>
                    <?php endif;
                    endif; ?>
                </li>
            <?php endforeach; ?>
                
        </ul>
            
    <?php }else{ ?>
        <hr>
        <p><?php echo $this->translate('Products are disabled for this program'); ?></p>
    <?php }