<?php
$title = 'Program Types';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
<a href="<?php echo $this->url('bkd-rwd/default', array('controller' => 'program', 'action'=>'index'), false);?>">&lt; Back to the programs | </a>
    <a href="<?php echo $this->url('bkd-rwd/default', array('controller' => 'category', 'action'=>'add'));?>">Add new Program Type </a>
	
</p>
<?php
if($categories)
{
echo '<table class="table">';
echo '<tr>';
echo '<th>Name</th>';
echo '<th>Count of programs </th>';
echo '<th>&nbsp;</th>';
echo '</tr>';
}
else
{
	echo 'There no categories';
}

foreach ($categories as $category) { ?>
<tr>
    <td><?php echo $this->escapeHtml($category->getName());?></td>
	<td><?php echo $this->escapeHtml(count($category->getPrograms()));?></td>
    <td>
		<a href="<?php echo $this->url('bkd-rwd/default',
            array('controller' => 'category', 'action'=>'view', 'id' => $category->getId()));?>">View programs</a>
		<a href="<?php echo $this->url('bkd-rwd/default', 
            array('controller' => 'category', 'action'=>'edit', 'id' => $category->getId()));?>">Edit</a>
        <a href="<?php echo $this->url('bkd-rwd/default', 
            array('controller' => 'category', 'action'=>'delete', 'id' => $category->getId()));?>" onclick="return confirm('Do you really want to delete this record?')">Delete</a>
    </td>
</tr>
<?php } ?>
</table>